export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const SHOW_MODAL_FORM = 'SHOW_MODAL_FORM';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_PASSWORD_CHANGED = 'USER_INPUT_PASSWORD_CHANGED';