export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const SHOW_MODAL_FORM = 'SHOW_MODAL_FORM';
export const CLOSE_MODAL_FORM = 'CLOSE_MODAL_FORM';

export const ON_LOGIN_ARRAY_SEARH = 'ON_LOGIN_ARRAY_SEARH';

export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_PASSWORD_CHANGED = 'USER_INPUT_PASSWORD_CHANGED';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';