export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_PASSWORD_CHANGED = 'USER_INPUT_PASSWORD_CHANGED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_LOGIN_MASSAGE = 'USER_LOGIN_MASSAGE';