export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const CLICK_POST = 'CLICK_POST';
export const SET_SELECTED_POST = 'SET_SELECTED_POST';

export const USER_INPUT_TITLE_CHANGED = 'USER_INPUT_TITLE_CHANGED';
export const USER_INPUT_TEXT_CHANGED = 'USER_INPUT_TEXT_CHANGED';
export const SET_MODIFIED_FORM = 'SET_MODIFIED_FORM';